name: Update Cucumber Reports Index

on:
  push:
    paths:
      - 'cucumber-report-viewer/public/TestResultsJsons/*.json'
      - '!cucumber-report-viewer/public/TestResultsJsons/index.json'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate index.json for Cucumber reports
        run: |
          cd cucumber-report-viewer/public/TestResultsJsons
          node ../../../../.github/scripts/generate-index.js

      - name: Commit and push index.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-update index.json for Cucumber reports'
          file_pattern: 'cucumber-report-viewer/public/TestResultsJsons/index.json'
